name: Publish Gradle outputs
description: Publish Gradle reports as workflow artifacts

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: Build results
        path: |
          **/build/reports/**
          **/build/distributions/*
          **/build/libs/*
