#!/bin/sh
# prerm script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

package_type=deb
COMMON_SCRIPTS
DESKTOP_SCRIPTS
LAUNCHER_AS_SERVICE_SCRIPTS

uninstall_andlogview() {
  DESKTOP_COMMANDS_UNINSTALL
  LAUNCHER_AS_SERVICE_COMMANDS_UNINSTALL

  # Remove icons from the system icons
  XDG_ICON_RESOURCE="`command -v xdg-icon-resource 2> /dev/null || true`"
  if [ ! -x "$XDG_ICON_RESOURCE" ]; then
    echo "Error: Could not find xdg-icon-resource" >&2
    exit 1
  fi
  for icon in andlogview.16.png andlogview.24.png andlogview.png andlogview.48.png andlogview.64.png andlogview.128.png andlogview.256.png; do
    size="$(echo ${icon} | sed 's/[^0-9]//g')"
    size=${size:-32}
    "$XDG_ICON_RESOURCE" uninstall --size "${size}" "name.mlopatkin-andlogview"
  done

  rm -f /usr/share/icons/hicolor/scalable/apps/name.mlopatkin-andlogview.svg

  UPDATE_MENUS="`command -v update-menus 2> /dev/null || true`"
  if [ -x "$UPDATE_MENUS" ]; then
    update-menus
  fi

  # Update cache of .desktop file MIME types. Non-fatal since it's just a cache.
  update-desktop-database > /dev/null 2>&1 || true

  rm /usr/bin/APPLICATION_PACKAGE || true
}

case "$1" in
    remove|upgrade|deconfigure)

    uninstall_andlogview
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
