name: Snapshot release build
on:
  push:
    branches:
      - master
jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    container: ghcr.io/mlopatkin/andlogview-build-environment@sha256:e30a7aaba23b1ae1abc90018eba4bdd148baee3faa975d0c84fed4009d4b30f3
    env:
      PYTHON_BINARY: python3
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/common-linux-setup
      - name: Build and publish snapshot
        # Do not use Gradle Daemon because we only have a single invocation and the running daemon interferes with the
        # caches.
        run: >
          ./gradlew
          -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
          --no-daemon
          --stacktrace
          check bitbucketUpload
        env:
          BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
          BITBUCKET_USER: mlopatkin
      - name: Publish artifacts
        uses: ./.github/actions/publish-gradle-outputs
      - name: Publish Github release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        if: ${{ success() }}
        with:
          files: build/distributions/*
          prerelease: true
          automatic_release_tag: "latest-snapshot"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
